services:
    vite-quart-example:
        container_name: vite-quart-example
        hostname: vite-container
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        image: vite-quart-example
        restart: unless-stopped
        ports:
            - "5001:5001" # production and backend
            - "5173:5173" # for vite dev server
        environment:
            # 502 is default on macos, 1000 on linux
            USER_ID: 1000
            GROUP_ID: 1000
        volumes:
            # we put the beets and our vite-quart-example config into the /config directory
            # create these folders before starting the container! otherwise you might
            # get permission issues.
            - ./config/:/config

            # for development. (disable if target is `prod`)
            - ./:/repo/
